/*
 * AIS API
 * Account Information Service Provider API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apigate@dskbank.bg
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Transactions;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AccountReport
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-27T12:18:16.648Z")
public class AccountReport {
  @SerializedName("booked")
  private List<Transactions> booked = new ArrayList<Transactions>();

  @SerializedName("pending")
  private List<Transactions> pending = null;

  public AccountReport booked(List<Transactions> booked) {
    this.booked = booked;
    return this;
  }

  public AccountReport addBookedItem(Transactions bookedItem) {
    this.booked.add(bookedItem);
    return this;
  }

   /**
   * Get booked
   * @return booked
  **/
  @ApiModelProperty(required = true, value = "")
  public List<Transactions> getBooked() {
    return booked;
  }

  public void setBooked(List<Transactions> booked) {
    this.booked = booked;
  }

  public AccountReport pending(List<Transactions> pending) {
    this.pending = pending;
    return this;
  }

  public AccountReport addPendingItem(Transactions pendingItem) {
    if (this.pending == null) {
      this.pending = new ArrayList<Transactions>();
    }
    this.pending.add(pendingItem);
    return this;
  }

   /**
   * Get pending
   * @return pending
  **/
  @ApiModelProperty(value = "")
  public List<Transactions> getPending() {
    return pending;
  }

  public void setPending(List<Transactions> pending) {
    this.pending = pending;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountReport accountReport = (AccountReport) o;
    return Objects.equals(this.booked, accountReport.booked) &&
        Objects.equals(this.pending, accountReport.pending);
  }

  @Override
  public int hashCode() {
    return Objects.hash(booked, pending);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountReport {\n");
    
    sb.append("    booked: ").append(toIndentedString(booked)).append("\n");
    sb.append("    pending: ").append(toIndentedString(pending)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

