/*
 * AIS API
 * Account Information Service Provider API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apigate@dskbank.bg
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Links;
import java.io.IOException;

/**
 * Account
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-27T12:18:16.648Z")
public class Account {
  @SerializedName("resourceId")
  private String resourceId = null;

  @SerializedName("iban")
  private String iban = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("product")
  private String product = null;

  @SerializedName("currency")
  private String currency = null;

  @SerializedName("_links")
  private Links links = null;

  public Account resourceId(String resourceId) {
    this.resourceId = resourceId;
    return this;
  }

   /**
   * This is the data element to be used in the path when retrieving data from a dedicated account.
   * @return resourceId
  **/
  @ApiModelProperty(required = true, value = "This is the data element to be used in the path when retrieving data from a dedicated account.")
  public String getResourceId() {
    return resourceId;
  }

  public void setResourceId(String resourceId) {
    this.resourceId = resourceId;
  }

  public Account iban(String iban) {
    this.iban = iban;
    return this;
  }

   /**
   * IBAN of account
   * @return iban
  **/
  @ApiModelProperty(required = true, value = "IBAN of account")
  public String getIban() {
    return iban;
  }

  public void setIban(String iban) {
    this.iban = iban;
  }

  public Account name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name given by the bank or the PSU in OnlineBanking.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name given by the bank or the PSU in OnlineBanking.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Account product(String product) {
    this.product = product;
    return this;
  }

   /**
   * Product Name of the Bank for this account
   * @return product
  **/
  @ApiModelProperty(required = true, value = "Product Name of the Bank for this account")
  public String getProduct() {
    return product;
  }

  public void setProduct(String product) {
    this.product = product;
  }

  public Account currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * ISO 4217 code
   * @return currency
  **/
  @ApiModelProperty(required = true, value = "ISO 4217 code")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public Account links(Links links) {
    this.links = links;
    return this;
  }

   /**
   * Links to the account, which can be directly used for retrieving account information from this dedicated account. Links to “balances” and/or “transactions”
   * @return links
  **/
  @ApiModelProperty(value = "Links to the account, which can be directly used for retrieving account information from this dedicated account. Links to “balances” and/or “transactions”")
  public Links getLinks() {
    return links;
  }

  public void setLinks(Links links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Account account = (Account) o;
    return Objects.equals(this.resourceId, account.resourceId) &&
        Objects.equals(this.iban, account.iban) &&
        Objects.equals(this.name, account.name) &&
        Objects.equals(this.product, account.product) &&
        Objects.equals(this.currency, account.currency) &&
        Objects.equals(this.links, account.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceId, iban, name, product, currency, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Account {\n");
    
    sb.append("    resourceId: ").append(toIndentedString(resourceId)).append("\n");
    sb.append("    iban: ").append(toIndentedString(iban)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

