/*
 * AIS API
 * Account Information Service Provider API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apigate@dskbank.bg
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ErrorModelTppMessages;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ErrorModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-27T12:18:16.648Z")
public class ErrorModel {
  @SerializedName("tppMessages")
  private List<ErrorModelTppMessages> tppMessages = null;

  public ErrorModel tppMessages(List<ErrorModelTppMessages> tppMessages) {
    this.tppMessages = tppMessages;
    return this;
  }

  public ErrorModel addTppMessagesItem(ErrorModelTppMessages tppMessagesItem) {
    if (this.tppMessages == null) {
      this.tppMessages = new ArrayList<ErrorModelTppMessages>();
    }
    this.tppMessages.add(tppMessagesItem);
    return this;
  }

   /**
   * Get tppMessages
   * @return tppMessages
  **/
  @ApiModelProperty(value = "")
  public List<ErrorModelTppMessages> getTppMessages() {
    return tppMessages;
  }

  public void setTppMessages(List<ErrorModelTppMessages> tppMessages) {
    this.tppMessages = tppMessages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorModel errorModel = (ErrorModel) o;
    return Objects.equals(this.tppMessages, errorModel.tppMessages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tppMessages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorModel {\n");
    
    sb.append("    tppMessages: ").append(toIndentedString(tppMessages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

