/*
 * AIS API
 * Account Information Service Provider API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apigate@dskbank.bg
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Links
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-27T12:18:16.648Z")
public class Links {
  @SerializedName("scaRedirect")
  private String scaRedirect = null;

  @SerializedName("self")
  private String self = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("account")
  private String account = null;

  @SerializedName("balances")
  private String balances = null;

  @SerializedName("transactions")
  private String transactions = null;

  @SerializedName("first")
  private String first = null;

  @SerializedName("next")
  private String next = null;

  @SerializedName("previous")
  private String previous = null;

  @SerializedName("last")
  private String last = null;

  public Links scaRedirect(String scaRedirect) {
    this.scaRedirect = scaRedirect;
    return this;
  }

   /**
   * A link to a BDSK site where SCA is performed within the Redirect SCA approach.
   * @return scaRedirect
  **/
  @ApiModelProperty(value = "A link to a BDSK site where SCA is performed within the Redirect SCA approach.")
  public String getScaRedirect() {
    return scaRedirect;
  }

  public void setScaRedirect(String scaRedirect) {
    this.scaRedirect = scaRedirect;
  }

  public Links self(String self) {
    this.self = self;
    return this;
  }

   /**
   * The link to the resource created by the undergoing request. This link can be used to retrieve the resource data.
   * @return self
  **/
  @ApiModelProperty(value = "The link to the resource created by the undergoing request. This link can be used to retrieve the resource data.")
  public String getSelf() {
    return self;
  }

  public void setSelf(String self) {
    this.self = self;
  }

  public Links status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Links account(String account) {
    this.account = account;
    return this;
  }

   /**
   * A link to an account, which can be directly used for retrieving account information from this dedicated account.
   * @return account
  **/
  @ApiModelProperty(value = "A link to an account, which can be directly used for retrieving account information from this dedicated account.")
  public String getAccount() {
    return account;
  }

  public void setAccount(String account) {
    this.account = account;
  }

  public Links balances(String balances) {
    this.balances = balances;
    return this;
  }

   /**
   * A link to the resource providing the balance of a dedicated account.
   * @return balances
  **/
  @ApiModelProperty(value = "A link to the resource providing the balance of a dedicated account.")
  public String getBalances() {
    return balances;
  }

  public void setBalances(String balances) {
    this.balances = balances;
  }

  public Links transactions(String transactions) {
    this.transactions = transactions;
    return this;
  }

   /**
   * A link to the resource providing the transaction history of a dedicated account.
   * @return transactions
  **/
  @ApiModelProperty(value = "A link to the resource providing the transaction history of a dedicated account.")
  public String getTransactions() {
    return transactions;
  }

  public void setTransactions(String transactions) {
    this.transactions = transactions;
  }

  public Links first(String first) {
    this.first = first;
    return this;
  }

   /**
   * Navigation link for account reports.
   * @return first
  **/
  @ApiModelProperty(value = "Navigation link for account reports.")
  public String getFirst() {
    return first;
  }

  public void setFirst(String first) {
    this.first = first;
  }

  public Links next(String next) {
    this.next = next;
    return this;
  }

   /**
   * Navigation link for account reports.
   * @return next
  **/
  @ApiModelProperty(value = "Navigation link for account reports.")
  public String getNext() {
    return next;
  }

  public void setNext(String next) {
    this.next = next;
  }

  public Links previous(String previous) {
    this.previous = previous;
    return this;
  }

   /**
   * Navigation link for account reports.
   * @return previous
  **/
  @ApiModelProperty(value = "Navigation link for account reports.")
  public String getPrevious() {
    return previous;
  }

  public void setPrevious(String previous) {
    this.previous = previous;
  }

  public Links last(String last) {
    this.last = last;
    return this;
  }

   /**
   * Navigation link for account reports.
   * @return last
  **/
  @ApiModelProperty(value = "Navigation link for account reports.")
  public String getLast() {
    return last;
  }

  public void setLast(String last) {
    this.last = last;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Links links = (Links) o;
    return Objects.equals(this.scaRedirect, links.scaRedirect) &&
        Objects.equals(this.self, links.self) &&
        Objects.equals(this.status, links.status) &&
        Objects.equals(this.account, links.account) &&
        Objects.equals(this.balances, links.balances) &&
        Objects.equals(this.transactions, links.transactions) &&
        Objects.equals(this.first, links.first) &&
        Objects.equals(this.next, links.next) &&
        Objects.equals(this.previous, links.previous) &&
        Objects.equals(this.last, links.last);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scaRedirect, self, status, account, balances, transactions, first, next, previous, last);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Links {\n");
    
    sb.append("    scaRedirect: ").append(toIndentedString(scaRedirect)).append("\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    balances: ").append(toIndentedString(balances)).append("\n");
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("    first: ").append(toIndentedString(first)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("    previous: ").append(toIndentedString(previous)).append("\n");
    sb.append("    last: ").append(toIndentedString(last)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

